version: "3.1"
   
services:
  db:
    container_name: pos_srv
    image: postgres
    environment:
      - POSTGRES_DB=logistic
      - POSTGRES_USER=logistic
      - POSTGRES_PASSWORD=logistic
    volumes:
        - "../postgres:/var/lib/postgresql/data"
    ports:
      - "5000:5432"
  
  web:
    container_name: dj_srv
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "6090:8000"
    depends_on:
      - db
