version: "3.1"
   
services:  
  db:
    container_name: post_srv
    image: postgres
    environment:
      - POSTGRES_DB=post
      - POSTGRES_USER=post
      - POSTGRES_PASSWORD=post
    volumes:
      - ./postgress/:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: always

  web:
    container_name: dj_srv
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
      - 3000:3000
    restart: always
    links:
    - db
    - cache
    depends_on:
      - db
      - cache

  cache:
    image: memcached
    ports:
      - "11211:11211"
    entrypoint:
      - memcached
      - -m 128
