version: "3.1"
   
services:  
  web:
    container_name: dj_srv
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8100:8000
    restart: always
