version: "3.1"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=logistic
      - POSTGRES_USER=logistic
      - POSTGRES_PASSWORD=logistic
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "6090:8000"
    depends_on:
      - db
