# Generated by Django 2.2.17 on 2021-03-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_services_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='services_activ'),
        ),
        migrations.AlterField(
            model_name='servicescategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='category_is_active'),
        ),
    ]
