# Generated by Django 2.2.17 on 2021-03-11 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mainapp", "0004_services_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="создан")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="обновлен")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FM", "формируется"),
                            ("STP", "отправлен в обработку"),
                            ("PD", "оплачен"),
                            ("PRD", "обрабатывается"),
                            ("RDY", "готов к выдаче"),
                            ("CNC", "отменен"),
                        ],
                        default="FM",
                        max_length=3,
                        verbose_name="статус",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="активен")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "заказ",
                "verbose_name_plural": "заказы",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(default=0, verbose_name="количество")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="orderitems", to="ordersapp.Order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainapp.Services", verbose_name="продукт"
                    ),
                ),
            ],
        ),
    ]
