# Generated by Django 2.2.17 on 2021-02-15 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mainapp", "0002_fill_db"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Basket",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(default=0, verbose_name="quantity")),
                ("add_datetime", models.DateTimeField(auto_now_add=True, verbose_name="время добавления")),
                ("service", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mainapp.Services")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="basket", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
