# Generated by Django 2.2.17 on 2021-02-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='add_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create_date'),
        ),
    ]
