# Generated by Django 2.2.17 on 2021-03-24 03:42

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0006_auto_20210317_0348"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 3, 26, 3, 42, 50, 117050, tzinfo=utc), verbose_name="актуальность ключа"
            ),
        ),
    ]
